expose:
  type: ingress
  tls:
    enabled: true
    secretName: kongs-info-tls
  ingress:
    hosts:
      ui: mall.kongs.info
    annotations:
      kubernetes.io/ingress.class: nginx
  nodePort:
    port: 30002

persistence:
  enabled: true
  persistentVolumeClaim:
    database:
      existingClaim: ""
      storageClass: ""
      subPath: ""
      accessMode: ReadWriteOnce
      size: 1Gi

# imagePullSecrets:
#   - name: myreg

ui:
  image:
    repository: cnych/polling-ui
    tag: 0.0.3
    pullPolicy: IfNotPresent
  replicas: 1
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

api:
  image:
    repository: mall-admin
    tag: 1.0
    pullPolicy: IfNotPresent
  replicas: 1
  service:
    port:
# resources:
#  requests:
#    memory: 256Mi
#    cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Additional deployment annotations
  podAnnotations: {}

database:
  # if external database is used, set "type" to "external"
  # and fill the connection informations in "external" section
  type: external
  internal:
    image:
      repository: mysql
      tag: 5.7
    # 使用的数据库名称
    database: "polling"
    # 数据库用户
    username: "polling"
    # 数据库用户密码
    password: "polling321"
    # resources:
    #  requests:
    #    memory: 256Mi
    #    cpu: 100m
    nodeSelector: {}
    tolerations: []
    affinity: {}
  external:
    host: "mysql"
    port: "3306"
    username: "root"
    password: "root"
    database: "mall"
  ## Additional deployment annotations
  podAnnotations: {}
